---
title: "Untitled"
output: github_document
---


## Generla stuff
http://teachtogether.tech/
http://darribas.org/gds19/
https://github.com/rdpeng/courses

https://osf.io/j97zp/


Encontrat ejempls de reproducir articulos:
- Ejemplos imposibles
- Ejemplos medio posibles
- Ejemplos fáciles

https://rpubs.com/hrbrmstr


## Session 1


* Current research publications suffer from (Cosit 2019)
  * Low reproducibility, difficult re-ure
  * difficult follow-up computational analysis, data-driven searches
  * no deeper exploration/inspection 
  
## Tools

* [RStudio Cloud](https://rstudio.cloud/)
* [RPubs](https://rpubs.com/)
* [Shinyapps.io](https://www.shinyapps.io/)
* Makefile

## Other inputs

* Ejemplos de reproducibilidad en otros dominios: 
economía“Analyzing Financial and Economic Data with R"
https://www.msperlin.com/blog/post/2019-11-25-feedback-toc-afedr/ 
https://www.msperlin.com/pafdR/

* PodcastWorking scientist podcast: How technology can help solve science's reproducibility crisis
https://www.nature.com/articles/d41586-019-01333-0

* [granolarr: a reproducible resource for teaching geographic data science in R](https://sdesabbata.github.io/granolarr/)

* [This AI researcher is trying to ward off a reproducibility crisis](https://www.nature.com/articles/d41586-019-03895-5)

* [Reproducible big data science: A case study in continuous FAIRness](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0213013)


* [Impact of Social Sciences – To save the research literature, let’s make literature reviews reproducible](https://blogs.lse.ac.uk/impactofsocialsciences/2018/06/19/to-save-the-research-literature-lets-make-literature-reviews-reproducible/)


* Session 02: RRP - Preliminaries (3 hr.).
  * 02_01: A simple reproducible project workflow 
    * a guide to next session
    * Rationale: Follow steps in BES + your own
      * Follow steps in BES. Add your own when necesary. Custom per discipline
      * Introduce tools as necessary
      * Anotate steps with related literature and relevant papers, guides and resources
      * Introduce examples as necessary. Allow participants to explore tools, services. 
      * Ask student how they can use such tools for their reseach. How can they adapt such steps for 

  * 02_02: Before you start 
    * folder organisation - see rr-template repo
    * naming convention - see [naming things by Jenny Bryan](http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf), [Phd comic](http://phdcomics.com/comics/archive.php?comicid=1531)
    * version control software: git
    * set up online version control account: github
  * 02_03: First steps
    * Create folder structure. Clone & rename (TODO)
      * create (local) version control repository for the project
      * connect the local version control repository to an online verion control repository 
    * add/update README file
    * add/update notes/notes file
    * choose/add LICENCE
  * 02_04: Examples & discussion
  * 02_05: Tools & readings
    * Git 
    * Github - 
    * R 
    * Rstudio 
    * [RStudio Cloud](https://rstudio.cloud/)

* Session 03: RRP - Iterative workflow (3 hr.)
  * 03_01: Write code
    * keep scripts in order (01_download, 02_....)
    * never eve touch input/raw data
    * comment the code, issue track, etc.
    * testing and CI via WebHooks (GitHub-CI)
    * commit to version control
    * Syncr with your remote control repository 
    * ...and repeat again, and again
  * 03_02: Write reproducible notebooks/reports
    * Literate programming 
    * Markdown format - [see AirBnb example](https://bookdown.org/yihui/rmarkdown/basics-examples.html#airbnbs-knowledge-repository)  
    * Notebooks and Computational narratives
  * 03_03: Virtual containers
    * Issue: dependences, version, OS
    * Remote containers with Binder
    * Local containers with Docker
  * 03_04: Examples & Discussion
  * 03_05: Tools & readings
    * Markdown
    * Make
    * Binder
    * Docker
    
* Session 04: RRP - Writing and dissemination (3 hr.)
  * 04_01: Write scientific article
    * Notebooks for writing scientific articles
  * 04_02: Create additional resources
    * Notebooks for flexdashboards
    * Notebooks for presentations
  * 04_03: Examples & Discussion
  * 04_04: Tools & readings

* Session 05: RRP - Publication and archiving (3 hr.)
  * 05_01: Guidelines to write reproducible papers
    * AGILE guidelines
    * General rules/papers from literature
    * Cite code and data
  * 05_02: Publication of reproducible reports
    * Use of RPubs
    * Use of Shinyapps 
  * 05_03: Permanent archiving 
    * Archive data and code via WebHooks GitHub-Zenodo and get a DOI
    * Udpate README files with DOIs, links to remote containers, etc.
  * 05_04: Examples & Discussion  
  * 05_05: Tools & readings
    * Data repositories: Zenodo, r3registry
    * [Open Science Foundation](https://osf.io/)
    * [RPubs](https://rpubs.com/)
    * [Shinyapps.io](https://www.shinyapps.io/)
  
* Session 06: How to reproduce other's work & final project (4 hr.)
  * 06_01: How to read a research article
  * 06_02: How to read a research compendium
  * 06_03: Ideas for projects
    * types of reviews, cumulative reviews. R data package example
    * How to reproduce other's works
  * 06_04: Summary and discussion




* Training of scientists in computational research practices has not kept pace
* scientists who wish to reproduce research may lack the information or training they need to do so
* When results are produced by complex computational processes using large volumes of data, the methods section of a scientific paper is insufficient to convey the necessary information for others to reproduce the results. Additional information related to data, code, models, and computational analysis is needed for others to computationally reproduce the results.

*  having the reuse of research results as a goal requires the adoption of new research practices during the data analysis process. Such practices need to be tailored to the needs of each given discipline with its particular research environment, culture and idiosyncrasies


Box 1 Guiding principles towards reproducibility 

Source: https://www.nature.com/articles/s41567-018-0342-2#Tab1



tentative paper to be reproduced by me
==========
Mobile Phone Indicators and Their Relation to the Socioeconomic Organisation of Cities
Clémentine Cottineau 1,2,†,*  and Maarten Vanhoof 3,4,†
ISPRS Int. J. Geo-Inf. 2019, 8(1), 19; 
https://www.mdpi.com/2220-9964/8/1/19


Use case:
1/ World data + coronavirus. Animated barchart per country over time

2/ Evaluation of the potential incidence of COVID-19 and effectiveness of contention measures in Spain: a data-driven approach
- https://www.medrxiv.org/content/10.1101/2020.03.01.20029801v2
- https://zenodo.org/record/3701751#.XnJBA6hKjZs
- https://observatoriotransporte.mitma.gob.es/estudio-experimental
- ...email from Simona



